config/routes.rb
Rails.application.routes.draw do

  root "pins#index"

  resources :pins
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController

    def index
        @pins = Pin.all
    end

    def new
        @pin = Pin.new
    end

    def create
        @pin = Pin.new(pin_params)
        @pin.user = current_user

        if @pin.save
            redirect_to root_path
        else
            render :new
        end
    end

    private

    def pin_params
        params.require(:pin).permit(:title, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClonePinterest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Clone Pinterest</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <% if signed_in? %>
            <li class="nav-item active">
              <a class="nav-link"
                <%= link_to "Nuevo Pin", new_pin_path %>
              </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link"
                <%= link_to "Salir", destroy_user_session_path %>
              </a>
            </li>
          <% else %>
            <li class="nav-item active">
              <a class="nav-link"
                <%= link_to "Registrarse", new_user_registration_path %>
              </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link"
                <%= link_to "Ingresar", new_user_session_path %>
              </a>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled clearfix masonry">
    <% @pins.each do |pin|%>
        <div class="pin panel panel-default">
            <div class="panel-body">
                <img src="<%= pin.image_url %>" alt="<%= pin.title %>">
                <h2><%= pin.title %></h2>
                <p class="user">Publicado por <%= pin.user.email %> </p>
            </div>
        </div>
    <% end %>
</div>

app/views/pins/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <h1>Nuevo Pin</h1>

            <%= form_for @pin do |f| %>
                <div class="form-group">
                    <b><%= f.label :title %></b>
                    <%= f.text_field :title, class: "form-control" %>
                </div>
                <div class="form-group">
                    <b><%= f.label :image_url %></b>
                    <%= f.url_field :image_url, class: "form-control" %>
                </div>
                <div class="action">
                    <%= f.submit class: "btn btn-primary btn-lg btn-block" %>
                </div>
            <% end %>
        </div>
    </div>
</div>